//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Tracker.Data.Queries
{
    public static partial class TaskExtendedExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Tracker.Data.Entities.TaskExtended GetByKey(this System.Linq.IQueryable<Tracker.Data.Entities.TaskExtended> queryable, int taskId)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Tracker.Data.Entities.TaskExtended>;
            if (dbSet != null)
                return dbSet.Find(taskId);

            return queryable.FirstOrDefault(t => t.TaskId == taskId);
        }
    }
}
