//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Ugly.Data.Entities
{
    public partial class Template
    {
        public Template()
        {
            LinkTemplateDepends = new HashSet<TemplateDepend>();
            DependTemplateDepends = new HashSet<TemplateDepend>();
        }

        public int TemplateID { get; set; }
        public string TemplateName { get; set; }

        public virtual ICollection<TemplateDepend> LinkTemplateDepends { get; set; }
        public virtual ICollection<TemplateDepend> DependTemplateDepends { get; set; }
    }
}