//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Data
{
    public partial class PetshopContext
        : DbContext
    {
        public PetshopContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<Petshop.Data.Entities.Account> Accounts { get; set; }
        public DbSet<Petshop.Data.Entities.BannerData> BannerData { get; set; }
        public DbSet<Petshop.Data.Entities.Category> Categories { get; set; }
        public DbSet<Petshop.Data.Entities.Inventory> Inventories { get; set; }
        public DbSet<Petshop.Data.Entities.Item> Items { get; set; }
        public DbSet<Petshop.Data.Entities.Product> Products { get; set; }
        public DbSet<Petshop.Data.Entities.Supplier> Suppliers { get; set; }
        public DbSet<Petshop.Data.Entities.LineItem> LineItems { get; set; }
        public DbSet<Petshop.Data.Entities.Orders> Orders { get; set; }
        public DbSet<Petshop.Data.Entities.OrderStatus> OrderStatuses { get; set; }
        public DbSet<Petshop.Data.Entities.Profile> Profiles { get; set; }
        public DbSet<Petshop.Data.Entities.SignOn> SignOns { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.AccountMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.BannerDataMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.CategoryMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.InventoryMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.ItemMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.ProductMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.SupplierMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.LineItemMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.OrdersMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.OrderStatusMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.ProfileMap());
            modelBuilder.ApplyConfiguration(new Petshop.Data.Mapping.SignOnMap());

            InitializeMapping(modelBuilder);
        }

        partial void InitializeMapping(ModelBuilder modelBuilder);
    }
}