//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Ugly.Data
{
    public partial class UglyContext
        : DbContext
    {
        public UglyContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<Ugly.Data.Entities.ContactImport> ContactImports { get; set; }
        public DbSet<Ugly.Data.Entities.Department> Departments { get; set; }
        public DbSet<Ugly.Data.Entities.Employees> Employees { get; set; }
        public DbSet<Ugly.Data.Entities.Duplicate> Duplicates { get; set; }
        public DbSet<Ugly.Data.Entities.Duplicate1> Duplicate1s { get; set; }
        public DbSet<Ugly.Data.Entities.EmployeeDepartment> EmployeeDepartments { get; set; }
        public DbSet<Ugly.Data.Entities.GuidAuto> GuidAutos { get; set; }
        public DbSet<Ugly.Data.Entities.Keyword> Keywords { get; set; }
        public DbSet<Ugly.Data.Entities.Membership> Memberships { get; set; }
        public DbSet<Ugly.Data.Entities.Object> Objects { get; set; }
        public DbSet<Ugly.Data.Entities.OrderDocument> OrderDocuments { get; set; }
        public DbSet<Ugly.Data.Entities.Provider> Providers { get; set; }
        public DbSet<Ugly.Data.Entities.Query> Queries { get; set; }
        public DbSet<Ugly.Data.Entities.Role> Roles { get; set; }
        public DbSet<Ugly.Data.Entities.SqlTypes> SqlTypes { get; set; }
        public DbSet<Ugly.Data.Entities.TableExample> TableExamples { get; set; }
        public DbSet<Ugly.Data.Entities.Table1Test> Table1Tests { get; set; }
        public DbSet<Ugly.Data.Entities.Template> Templates { get; set; }
        public DbSet<Ugly.Data.Entities.TemplateDepend> TemplateDepends { get; set; }
        public DbSet<Ugly.Data.Entities.TwoForeignKey> TwoForeignKeys { get; set; }
        public DbSet<Ugly.Data.Entities.TwoKey> TwoKeys { get; set; }
        public DbSet<Ugly.Data.Entities.User> Users { get; set; }
        public DbSet<Ugly.Data.Entities.UserRole> UserRoles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.ContactImportMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.DepartmentMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.EmployeesMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.DuplicateMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.Duplicate1Map());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.EmployeeDepartmentMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.GuidAutoMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.KeywordMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.MembershipMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.ObjectMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.OrderDocumentMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.ProviderMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.QueryMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.RoleMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.SqlTypesMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.TableExampleMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.Table1TestMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.TemplateMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.TemplateDependMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.TwoForeignKeyMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.TwoKeyMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.UserMap());
            modelBuilder.ApplyConfiguration(new Ugly.Data.Mapping.UserRoleMap());

            InitializeMapping(modelBuilder);
        }

        partial void InitializeMapping(ModelBuilder modelBuilder);
    }
}