//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Petshop.Data.Mapping
{
    public partial class BannerDataMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Petshop.Data.Entities.BannerData>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.BannerData> builder)
        {
            // table
            builder.ToTable("BannerData", "dbo");

            // keys
            builder.HasKey(t => t.FavoriteCategory);

            // Properties
            builder.Property(t => t.FavoriteCategory)
                .IsRequired()
                .HasColumnName("FavCategory")
                .HasColumnType("varchar")
                .HasMaxLength(80)
                .ValueGeneratedNever();
            builder.Property(t => t.BannerDataMember)
                .HasColumnName("BannerData")
                .HasColumnType("varchar")
                .HasMaxLength(255);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.BannerData> builder);

    }
}
