//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Petshop.Data.Mapping
{
    public partial class CategoryMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Petshop.Data.Entities.Category>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.Category> builder)
        {
            // table
            builder.ToTable("Category", "dbo");

            // keys
            builder.HasKey(t => t.CategoryId);

            // Properties
            builder.Property(t => t.CategoryId)
                .IsRequired()
                .HasColumnName("CatId")
                .HasColumnType("varchar")
                .HasMaxLength(10)
                .ValueGeneratedNever();
            builder.Property(t => t.Name)
                .HasColumnName("Name")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.Description)
                .HasColumnName("Descn")
                .HasColumnType("varchar")
                .HasMaxLength(255);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.Category> builder);

    }
}
