//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Petshop.Data.Mapping
{
    public partial class InventoryMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Petshop.Data.Entities.Inventory>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.Inventory> builder)
        {
            // table
            builder.ToTable("Inventory", "dbo");

            // keys
            builder.HasKey(t => t.ItemId);

            // Properties
            builder.Property(t => t.ItemId)
                .IsRequired()
                .HasColumnName("ItemId")
                .HasColumnType("varchar")
                .HasMaxLength(10)
                .ValueGeneratedNever();
            builder.Property(t => t.Qty)
                .IsRequired()
                .HasColumnName("Qty")
                .HasColumnType("int");

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.Inventory> builder);

    }
}
