//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Petshop.Data.Mapping
{
    public partial class ItemMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Petshop.Data.Entities.Item>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.Item> builder)
        {
            // table
            builder.ToTable("Item", "dbo");

            // keys
            builder.HasKey(t => t.ItemId);

            // Properties
            builder.Property(t => t.ItemId)
                .IsRequired()
                .HasColumnName("ItemId")
                .HasColumnType("varchar")
                .HasMaxLength(10)
                .ValueGeneratedNever();
            builder.Property(t => t.ProductId)
                .IsRequired()
                .HasColumnName("ProductId")
                .HasColumnType("varchar")
                .HasMaxLength(10);
            builder.Property(t => t.ListPrice)
                .HasColumnName("ListPrice")
                .HasColumnType("decimal");
            builder.Property(t => t.UnitCost)
                .HasColumnName("UnitCost")
                .HasColumnType("decimal");
            builder.Property(t => t.Supplier)
                .HasColumnName("Supplier")
                .HasColumnType("int");
            builder.Property(t => t.Status)
                .HasColumnName("Status")
                .HasColumnType("varchar")
                .HasMaxLength(2);
            builder.Property(t => t.Attr1)
                .HasColumnName("Attr1")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.Attr2)
                .HasColumnName("Attr2")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.Attr3)
                .HasColumnName("Attr3")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.Attr4)
                .HasColumnName("Attr4")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.Attr5)
                .HasColumnName("Attr5")
                .HasColumnType("varchar")
                .HasMaxLength(80);

            // Relationships
            builder.HasOne(t => t.Product)
                .WithMany(t => t.Items)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__Item__ProductId__38996AB5");
            builder.HasOne(t => t.Supplier1)
                .WithMany(t => t.Items)
                .HasForeignKey(d => d.Supplier)
                .HasConstraintName("FK__Item__Supplier__398D8EEE");

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.Item> builder);

    }
}
