//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Petshop.Data.Mapping
{
    public partial class LineItemMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Petshop.Data.Entities.LineItem>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.LineItem> builder)
        {
            // table
            builder.ToTable("LineItem", "dbo");

            // keys
            builder.HasKey(t => new { t.OrderId, t.LineNum });

            // Properties
            builder.Property(t => t.OrderId)
                .IsRequired()
                .HasColumnName("OrderId")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.LineNum)
                .IsRequired()
                .HasColumnName("LineNum")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.ItemId)
                .IsRequired()
                .HasColumnName("ItemId")
                .HasColumnType("varchar")
                .HasMaxLength(10);
            builder.Property(t => t.Quantity)
                .IsRequired()
                .HasColumnName("Quantity")
                .HasColumnType("int");
            builder.Property(t => t.UnitPrice)
                .IsRequired()
                .HasColumnName("UnitPrice")
                .HasColumnType("decimal");

            // Relationships
            builder.HasOne(t => t.Orders)
                .WithMany(t => t.LineItems)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__LineItem__OrderI__3A81B327");

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.LineItem> builder);

    }
}
