//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Petshop.Data.Mapping
{
    public partial class OrderStatusMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Petshop.Data.Entities.OrderStatus>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.OrderStatus> builder)
        {
            // table
            builder.ToTable("OrderStatus", "dbo");

            // keys
            builder.HasKey(t => new { t.OrderId, t.LineNum });

            // Properties
            builder.Property(t => t.OrderId)
                .IsRequired()
                .HasColumnName("OrderId")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.LineNum)
                .IsRequired()
                .HasColumnName("LineNum")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.Timestamp)
                .IsRequired()
                .HasColumnName("Timestamp")
                .HasColumnType("datetime");
            builder.Property(t => t.Status)
                .IsRequired()
                .HasColumnName("Status")
                .HasColumnType("varchar")
                .HasMaxLength(2);

            // Relationships
            builder.HasOne(t => t.Orders)
                .WithMany(t => t.OrderStatuses)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__OrderStat__Order__3B75D760");

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.OrderStatus> builder);

    }
}
