//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Petshop.Data.Mapping
{
    public partial class SupplierMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Petshop.Data.Entities.Supplier>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.Supplier> builder)
        {
            // table
            builder.ToTable("Supplier", "dbo");

            // keys
            builder.HasKey(t => t.SuppId);

            // Properties
            builder.Property(t => t.SuppId)
                .IsRequired()
                .HasColumnName("SuppId")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.Name)
                .HasColumnName("Name")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.Status)
                .IsRequired()
                .HasColumnName("Status")
                .HasColumnType("varchar")
                .HasMaxLength(2);
            builder.Property(t => t.Addr1)
                .HasColumnName("Addr1")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.Addr2)
                .HasColumnName("Addr2")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.City)
                .HasColumnName("City")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.State)
                .HasColumnName("State")
                .HasColumnType("varchar")
                .HasMaxLength(80);
            builder.Property(t => t.Zip)
                .HasColumnName("Zip")
                .HasColumnType("varchar")
                .HasMaxLength(5);
            builder.Property(t => t.Phone)
                .HasColumnName("Phone")
                .HasColumnType("varchar")
                .HasMaxLength(40);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Petshop.Data.Entities.Supplier> builder);

    }
}
