//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ugly.Data.Queries
{
    public static partial class DepartmentExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Ugly.Data.Entities.Department GetByKey(this System.Linq.IQueryable<Ugly.Data.Entities.Department> queryable, int departmentId)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Ugly.Data.Entities.Department>;
            if (dbSet != null)
                return dbSet.Find(departmentId);

            return queryable.FirstOrDefault(d => d.DepartmentId == departmentId);
        }

        public static IQueryable<Ugly.Data.Entities.Department> ByCreatedBy(this IQueryable<Ugly.Data.Entities.Department> queryable, int createdBy)
        {
            return queryable.Where(d => d.CreatedBy == createdBy);
        }

        public static IQueryable<Ugly.Data.Entities.Department> ByUpdatedBy(this IQueryable<Ugly.Data.Entities.Department> queryable, int updatedBy)
        {
            return queryable.Where(d => d.UpdatedBy == updatedBy);
        }
    }
}
