//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ugly.Data.Queries
{
    public static partial class EmployeesExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Ugly.Data.Entities.Employees GetByKey(this System.Linq.IQueryable<Ugly.Data.Entities.Employees> queryable, int employeeId)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Ugly.Data.Entities.Employees>;
            if (dbSet != null)
                return dbSet.Find(employeeId);

            return queryable.FirstOrDefault(e => e.EmployeeId == employeeId);
        }

        public static IQueryable<Ugly.Data.Entities.Employees> ByManagerId(this IQueryable<Ugly.Data.Entities.Employees> queryable, int? managerId)
        {
            return queryable.Where(e => (e.ManagerId == managerId || (managerId == null && e.ManagerId == null)));
        }

        public static IQueryable<Ugly.Data.Entities.Employees> ByCreatedBy(this IQueryable<Ugly.Data.Entities.Employees> queryable, int createdBy)
        {
            return queryable.Where(e => e.CreatedBy == createdBy);
        }

        public static IQueryable<Ugly.Data.Entities.Employees> ByUpdatedBy(this IQueryable<Ugly.Data.Entities.Employees> queryable, int updatedBy)
        {
            return queryable.Where(e => e.UpdatedBy == updatedBy);
        }
    }
}
