//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ugly.Data.Queries
{
    public static partial class EmployeeDepartmentExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Ugly.Data.Entities.EmployeeDepartment GetByKey(this System.Linq.IQueryable<Ugly.Data.Entities.EmployeeDepartment> queryable, int departmentId, int employeeId)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Ugly.Data.Entities.EmployeeDepartment>;
            if (dbSet != null)
                return dbSet.Find(departmentId, employeeId);

            return queryable.FirstOrDefault(e => e.DepartmentId == departmentId
                && e.EmployeeId == employeeId);
        }

        public static IQueryable<Ugly.Data.Entities.EmployeeDepartment> ByDepartmentId(this IQueryable<Ugly.Data.Entities.EmployeeDepartment> queryable, int departmentId)
        {
            return queryable.Where(e => e.DepartmentId == departmentId);
        }

        public static IQueryable<Ugly.Data.Entities.EmployeeDepartment> ByEmployeeId(this IQueryable<Ugly.Data.Entities.EmployeeDepartment> queryable, int employeeId)
        {
            return queryable.Where(e => e.EmployeeId == employeeId);
        }

        public static IQueryable<Ugly.Data.Entities.EmployeeDepartment> ByCreatedBy(this IQueryable<Ugly.Data.Entities.EmployeeDepartment> queryable, int createdBy)
        {
            return queryable.Where(e => e.CreatedBy == createdBy);
        }

        public static IQueryable<Ugly.Data.Entities.EmployeeDepartment> ByUpdatedBy(this IQueryable<Ugly.Data.Entities.EmployeeDepartment> queryable, int updatedBy)
        {
            return queryable.Where(e => e.UpdatedBy == updatedBy);
        }
    }
}
