//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ugly.Data.Queries
{
    public static partial class GuidAutoExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Ugly.Data.Entities.GuidAuto GetByKey(this System.Linq.IQueryable<Ugly.Data.Entities.GuidAuto> queryable, Guid guidID)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Ugly.Data.Entities.GuidAuto>;
            if (dbSet != null)
                return dbSet.Find(guidID);

            return queryable.FirstOrDefault(g => g.GuidID == guidID);
        }
    }
}
