//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ugly.Data.Queries
{
    public static partial class OrderDocumentExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Ugly.Data.Entities.OrderDocument GetByKey(this System.Linq.IQueryable<Ugly.Data.Entities.OrderDocument> queryable, int orderID, int documentID)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Ugly.Data.Entities.OrderDocument>;
            if (dbSet != null)
                return dbSet.Find(orderID, documentID);

            return queryable.FirstOrDefault(o => o.OrderID == orderID
                && o.DocumentID == documentID);
        }
    }
}
