//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ugly.Data.Queries
{
    public static partial class TemplateDependExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Ugly.Data.Entities.TemplateDepend GetByKey(this System.Linq.IQueryable<Ugly.Data.Entities.TemplateDepend> queryable, int linkID, int dependID)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Ugly.Data.Entities.TemplateDepend>;
            if (dbSet != null)
                return dbSet.Find(linkID, dependID);

            return queryable.FirstOrDefault(t => t.LinkID == linkID
                && t.DependID == dependID);
        }

        public static IQueryable<Ugly.Data.Entities.TemplateDepend> ByLinkID(this IQueryable<Ugly.Data.Entities.TemplateDepend> queryable, int linkID)
        {
            return queryable.Where(t => t.LinkID == linkID);
        }

        public static IQueryable<Ugly.Data.Entities.TemplateDepend> ByDependID(this IQueryable<Ugly.Data.Entities.TemplateDepend> queryable, int dependID)
        {
            return queryable.Where(t => t.DependID == dependID);
        }
    }
}
