//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ugly.Data.Queries
{
    public static partial class UserRoleExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Ugly.Data.Entities.UserRole GetByKey(this System.Linq.IQueryable<Ugly.Data.Entities.UserRole> queryable, int id)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Ugly.Data.Entities.UserRole>;
            if (dbSet != null)
                return dbSet.Find(id);

            return queryable.FirstOrDefault(u => u.Id == id);
        }

        public static IQueryable<Ugly.Data.Entities.UserRole> ByUserId(this IQueryable<Ugly.Data.Entities.UserRole> queryable, int userId)
        {
            return queryable.Where(u => u.UserId == userId);
        }

        public static IQueryable<Ugly.Data.Entities.UserRole> ByUserName(this IQueryable<Ugly.Data.Entities.UserRole> queryable, string userName)
        {
            return queryable.Where(u => u.UserName == userName);
        }

        public static IQueryable<Ugly.Data.Entities.UserRole> ByRoleId(this IQueryable<Ugly.Data.Entities.UserRole> queryable, int roleId)
        {
            return queryable.Where(u => u.RoleId == roleId);
        }
    }
}
