//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Petshop.Data.Queries
{
    public static partial class BannerDataExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static Petshop.Data.Entities.BannerData GetByKey(this System.Linq.IQueryable<Petshop.Data.Entities.BannerData> queryable, string favoriteCategory)
        {
            var dbSet = queryable as Microsoft.EntityFrameworkCore.DbSet<Petshop.Data.Entities.BannerData>;
            if (dbSet != null)
                return dbSet.Find(favoriteCategory);

            return queryable.FirstOrDefault(b => b.FavoriteCategory == favoriteCategory);
        }
    }
}
