//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class ContactImportMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.ContactImport>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.ContactImport> builder)
        {
            // table
            builder.ToTable("ContactImport", "dbo");

            // keys

            // Properties
            builder.Property(t => t.FirstName)
                .HasColumnName("FirstName")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.LastName)
                .HasColumnName("LastName")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.Address1)
                .HasColumnName("Address1")
                .HasColumnType("varchar")
                .HasMaxLength(150);
            builder.Property(t => t.Address2)
                .HasColumnName("Address2")
                .HasColumnType("varchar")
                .HasMaxLength(150);
            builder.Property(t => t.City)
                .HasColumnName("City")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.State)
                .HasColumnName("State")
                .HasColumnType("varchar")
                .HasMaxLength(2);
            builder.Property(t => t.Zip)
                .HasColumnName("Zip")
                .HasColumnType("varchar")
                .HasMaxLength(10);
            builder.Property(t => t.Email)
                .HasColumnName("Email")
                .HasColumnType("varchar")
                .HasMaxLength(150);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.ContactImport> builder);

    }
}
