//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class DepartmentMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.Department>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Department> builder)
        {
            // table
            builder.ToTable("Department", "dbo");

            // keys
            builder.HasKey(t => t.DepartmentId);

            // Properties
            builder.Property(t => t.DepartmentId)
                .IsRequired()
                .HasColumnName("DepartmentId")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            builder.Property(t => t.Name)
                .IsRequired()
                .HasColumnName("Name")
                .HasColumnType("varbinary")
                .HasMaxLength(50);
            builder.Property(t => t.Description)
                .HasColumnName("Description")
                .HasColumnType("varbinary")
                .HasMaxLength(50);
            builder.Property(t => t.CreatedBy)
                .IsRequired()
                .HasColumnName("CreatedBy")
                .HasColumnType("int");
            builder.Property(t => t.UpdatedBy)
                .IsRequired()
                .HasColumnName("UpdatedBy")
                .HasColumnType("int");

            // Relationships
            builder.HasOne(t => t.CreatedByEmployees)
                .WithMany(t => t.CreatedByDepartments)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_Department_Employees");
            builder.HasOne(t => t.UpdatedByEmployees)
                .WithMany(t => t.UpdatedByDepartments)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK_Department_Employees1");

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Department> builder);

    }
}
