//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class DuplicateMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.Duplicate>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Duplicate> builder)
        {
            // table
            builder.ToTable("Duplicate", "dbo");

            // keys
            builder.HasKey(t => t.DuplicateID);

            // Properties
            builder.Property(t => t.DuplicateID)
                .IsRequired()
                .HasColumnName("DuplicateID")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            builder.Property(t => t.DuplicateName)
                .HasColumnName("DuplicateName")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.DuplicateName1)
                .HasColumnName("Duplicate_Name")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.DuplicateMember)
                .HasColumnName("Duplicate")
                .HasColumnType("varchar")
                .HasMaxLength(50);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Duplicate> builder);

    }
}
