//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class EmployeeDepartmentMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.EmployeeDepartment>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.EmployeeDepartment> builder)
        {
            // table
            builder.ToTable("EmployeeDepartment", "dbo");

            // keys
            builder.HasKey(t => new { t.DepartmentId, t.EmployeeId });

            // Properties
            builder.Property(t => t.DepartmentId)
                .IsRequired()
                .HasColumnName("DepartmentId")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            builder.Property(t => t.EmployeeId)
                .IsRequired()
                .HasColumnName("EmployeeId")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.CreatedBy)
                .IsRequired()
                .HasColumnName("CreatedBy")
                .HasColumnType("int");
            builder.Property(t => t.UpdatedBy)
                .IsRequired()
                .HasColumnName("UpdatedBy")
                .HasColumnType("int");

            // Relationships
            builder.HasOne(t => t.Department)
                .WithMany(t => t.EmployeeDepartments)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_EmployeeDepartment_Department");
            builder.HasOne(t => t.Employees)
                .WithMany(t => t.EmployeeDepartments)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK_EmployeeDepartment_Employees");
            builder.HasOne(t => t.CreatedByEmployees)
                .WithMany(t => t.CreatedByEmployeeDepartments)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_EmployeeDepartment_Employees1");
            builder.HasOne(t => t.UpdatedByEmployees)
                .WithMany(t => t.UpdatedByEmployeeDepartments)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK_EmployeeDepartment_Employees2");

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.EmployeeDepartment> builder);

    }
}
