//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class EmployeesMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.Employees>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Employees> builder)
        {
            // table
            builder.ToTable("Employees", "dbo");

            // keys
            builder.HasKey(t => t.EmployeeId);

            // Properties
            builder.Property(t => t.EmployeeId)
                .IsRequired()
                .HasColumnName("EmployeeId")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            builder.Property(t => t.FirstName)
                .IsRequired()
                .HasColumnName("FirstName")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.LastName)
                .IsRequired()
                .HasColumnName("LastName")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.Email)
                .HasColumnName("Email")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.ManagerId)
                .HasColumnName("ManagerId")
                .HasColumnType("int");
            builder.Property(t => t.CreatedBy)
                .IsRequired()
                .HasColumnName("CreatedBy")
                .HasColumnType("int");
            builder.Property(t => t.UpdatedBy)
                .IsRequired()
                .HasColumnName("UpdatedBy")
                .HasColumnType("int");

            // Relationships
            builder.HasOne(t => t.ManagerEmployees)
                .WithMany(t => t.ManagerEmployees1)
                .HasForeignKey(d => d.ManagerId)
                .HasConstraintName("FK_Employees_Employees");
            builder.HasOne(t => t.CreatedByEmployees)
                .WithMany(t => t.CreatedByEmployees1)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_Employees_Employees1");
            builder.HasOne(t => t.UpdatedByEmployees)
                .WithMany(t => t.UpdatedByEmployees1)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK_Employees_Employees2");

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Employees> builder);

    }
}
