//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class GuidAutoMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.GuidAuto>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.GuidAuto> builder)
        {
            // table
            builder.ToTable("GuidAuto", "dbo");

            // keys
            builder.HasKey(t => t.GuidID);

            // Properties
            builder.Property(t => t.GuidID)
                .IsRequired()
                .HasColumnName("GuidID")
                .HasColumnType("uniqueidentifier")
                .HasDefaultValueSql("(newid())")
                .ValueGeneratedNever();
            builder.Property(t => t.AutoID)
                .IsRequired()
                .HasColumnName("AutoID")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            builder.Property(t => t.Name)
                .IsRequired()
                .HasColumnName("Name")
                .HasColumnType("varchar")
                .HasMaxLength(50);
            builder.Property(t => t.Flag)
                .IsRequired()
                .IsRowVersion()
                .HasColumnName("Flag")
                .HasColumnType("timestamp")
                .HasMaxLength(8)
                .ValueGeneratedOnAddOrUpdate();

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.GuidAuto> builder);

    }
}
