//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class KeywordMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.Keyword>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Keyword> builder)
        {
            // table
            builder.ToTable("Keyword", "dbo");

            // keys
            builder.HasKey(t => t.Private);

            // Properties
            builder.Property(t => t.Private)
                .IsRequired()
                .HasColumnName("Private")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.Public)
                .HasColumnName("Public")
                .HasColumnType("int");
            builder.Property(t => t.KeywordMember)
                .HasColumnName("Keyword")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);
            builder.Property(t => t.Namespace)
                .HasColumnName("namespace")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Keyword> builder);

    }
}
