//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class OrderDocumentMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.OrderDocument>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.OrderDocument> builder)
        {
            // table
            builder.ToTable("OrderDocument", "dbo");

            // keys
            builder.HasKey(t => new { t.OrderID, t.DocumentID });

            // Properties
            builder.Property(t => t.OrderID)
                .IsRequired()
                .HasColumnName("OrderID")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.DocumentID)
                .IsRequired()
                .HasColumnName("DocumentID")
                .HasColumnType("int")
                .ValueGeneratedNever();

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.OrderDocument> builder);

    }
}
