//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class Table1TestMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.Table1Test>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Table1Test> builder)
        {
            // table
            builder.ToTable("Table1 $ Test", "dbo");

            // keys
            builder.HasKey(t => t.Test);

            // Properties
            builder.Property(t => t.Test)
                .IsRequired()
                .HasColumnName("Test$")
                .HasColumnType("char")
                .HasMaxLength(10)
                .ValueGeneratedNever();
            builder.Property(t => t.Blah)
                .HasColumnName("Blah #")
                .HasColumnType("char")
                .HasMaxLength(10);
            builder.Property(t => t.TableExampleID)
                .HasColumnName("Table Example ID")
                .HasColumnType("int");
            builder.Property(t => t.TableExampleObject)
                .HasColumnName("TableExampleObject")
                .HasColumnType("int");
            builder.Property(t => t.StNumber)
                .HasColumnName("1stNumber")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);
            builder.Property(t => t.Street)
                .HasColumnName("123Street")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);
            builder.Property(t => t.Test123)
                .HasColumnName("123 Test 123")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Table1Test> builder);

    }
}
