//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class TableExampleMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.TableExample>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.TableExample> builder)
        {
            // table
            builder.ToTable("Table Example", "dbo");

            // keys
            builder.HasKey(t => t.TableExampleID);

            // Properties
            builder.Property(t => t.TableExampleID)
                .IsRequired()
                .HasColumnName("Table Example ID")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            builder.Property(t => t.NameExample)
                .IsRequired()
                .HasColumnName("Name Example")
                .HasColumnType("varchar")
                .HasMaxLength(50);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.TableExample> builder);

    }
}
