//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class TemplateMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.Template>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Template> builder)
        {
            // table
            builder.ToTable("Template", "dbo");

            // keys
            builder.HasKey(t => t.TemplateID);

            // Properties
            builder.Property(t => t.TemplateID)
                .IsRequired()
                .HasColumnName("TemplateID")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            builder.Property(t => t.TemplateName)
                .HasColumnName("TemplateName")
                .HasColumnType("varchar")
                .HasMaxLength(50);

            // Relationships

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.Template> builder);

    }
}
