//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class TemplateDependMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.TemplateDepend>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.TemplateDepend> builder)
        {
            // table
            builder.ToTable("TemplateDepend", "dbo");

            // keys
            builder.HasKey(t => new { t.LinkID, t.DependID });

            // Properties
            builder.Property(t => t.LinkID)
                .IsRequired()
                .HasColumnName("LinkID")
                .HasColumnType("int")
                .ValueGeneratedNever();
            builder.Property(t => t.DependID)
                .IsRequired()
                .HasColumnName("DependID")
                .HasColumnType("int")
                .ValueGeneratedNever();

            // Relationships
            builder.HasOne(t => t.LinkTemplate)
                .WithMany(t => t.LinkTemplateDepends)
                .HasForeignKey(d => d.LinkID)
                .HasConstraintName("FK_TemplateDepend_Template");
            builder.HasOne(t => t.DependTemplate)
                .WithMany(t => t.DependTemplateDepends)
                .HasForeignKey(d => d.DependID)
                .HasConstraintName("FK_TemplateDepend_Template1");

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.TemplateDepend> builder);

    }
}
