//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace Ugly.Data.Mapping
{
    public partial class TwoForeignKeyMap
        : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Ugly.Data.Entities.TwoForeignKey>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.TwoForeignKey> builder)
        {
            // table
            builder.ToTable("TwoForeignKey", "dbo");

            // keys
            builder.HasKey(t => t.Id);

            // Properties
            builder.Property(t => t.Id)
                .IsRequired()
                .HasColumnName("Id")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            builder.Property(t => t.FirstName)
                .IsRequired()
                .HasColumnName("FirstName")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);
            builder.Property(t => t.LastName)
                .IsRequired()
                .HasColumnName("LastName")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);
            builder.Property(t => t.Address)
                .HasColumnName("Address")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);
            builder.Property(t => t.Blah)
                .HasColumnName("Blah")
                .HasColumnType("nvarchar")
                .HasMaxLength(50);

            // Relationships
            builder.HasOne(t => t.TwoKey)
                .WithMany(t => t.TwoForeignKeys)
                .HasForeignKey(d => new { d.FirstName, d.LastName })
                .HasConstraintName("FK_TwoForeignKey_TwoKey");

            InitializeMapping(builder);
        }

        partial void InitializeMapping(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Ugly.Data.Entities.TwoForeignKey> builder);

    }
}
